export const routes = {
    apiUrl: 'https://localhost:7285/api',
    home: '/home',
    users: '/users',
    courses: '/courses',
    groups: '/Groups',
    chatApi: 'https://localhost:7285/chat',
    chat: '/chat',
    notificationHub:'https://localhost:7285/notification',
    students: '/Students',
    management: '/Management',
    subjects: '/Subjects',
    learning: '/Learning',
    topics: '/Topics',
};